# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

characters = [
  { name: 'Abigail', birthday: 'Fall 13' },
  { name: 'Alex', birthday: 'Summer 13' },
  { name: 'Elliott', birthday: 'Fall 5' },
  { name: 'Emily', birthday: 'Spring 27' },
  { name: 'Haley', birthday: 'Spring 14' },
  { name: 'Harvey', birthday: 'Winter 14' },
  { name: 'Leah', birthday: 'Winter 23' },
  { name: 'Maru', birthday: 'Summer 10' },
  { name: 'Penny', birthday: 'Fall 2' },
  { name: 'Sam', birthday: 'Summer 17' },
  { name: 'Sebastian', birthday: 'Winter 10' },
  { name: 'Shane', birthday: 'Spring 20' },
  { name: 'Caroline', birthday: 'Winter 7' },
  { name: 'Clint', birthday: 'Winter 26' },
  { name: 'Demetrius', birthday: 'Summer 19' },
  { name: 'Dwarf', birthday: 'Summer 22' },
  { name: 'Evelyn', birthday: 'Winter 20' },
  { name: 'George', birthday: 'Fall 24' },
  { name: 'Gus', birthday: 'Summer 8' },
  { name: 'Jas', birthday: 'Summer 4' },
  { name: 'Jodi', birthday: 'Fall 11' },
  { name: 'Kent', birthday: 'Spring 4' },
  { name: 'Krobus', birthday: 'Winter 1' },
  { name: 'Leo', birthday: 'Summer 26' },
  { name: 'Lewis', birthday: 'Spring 7' },
  { name: 'Linus', birthday: 'Winter 3' },
  { name: 'Marnie', birthday: 'Fall 18' },
  { name: 'Pam', birthday: 'Spring 18' },
  { name: 'Pierre', birthday: 'Spring 26' },
  { name: 'Robin', birthday: 'Fall 21' },
  { name: 'Sandy', birthday: 'Fall 15' },
  { name: 'Vincent', birthday: 'Spring 10' },
  { name: 'Willy', birthday: 'Summer 24' },
  { name: 'Wizard', birthday: 'Winter 17' }
]

characters.each do |character|
    Character.find_or_create_by(character)
end

hobbies = [
  { slug: 'flute', name: 'playing flute' },
  { slug: 'mining', name: 'mining' },
  { slug: 'playing-video-games', name: 'playing video games' },
  { slug: 'playing-football', name: 'playing football' },
  { slug: 'working-out', name: 'working out' },
  { slug: 'cooking', name: 'cooking' },
  { slug: 'writing', name: 'writing' },
  { slug: 'reading', name: 'reading' },
  { slug: 'fishing', name: 'fishing' },
  { slug: 'sewing', name: 'sewing' },
  { slug: 'making-clothes', name: 'making clothes' },
  { slug: 'baking', name: 'baking' },
  { slug: 'photography', name: 'photography' },
  { slug: 'shopping', name: 'shopping' },
  { slug: 'sunbathing', name: 'sunbathing' },
  { slug: 'medicine', name: 'medicine' },
  { slug: 'flying-drones', name: 'flying drones' },
  { slug: 'painting', name: 'painting' },
  { slug: 'sculpting', name: 'sculpting' },
  { slug: 'foraging', name: 'foraging' },
  { slug: 'inventing', name: 'inventing' },
  { slug: 'building-robots', name: 'building robots' },
  { slug: 'helping-others', name: 'helping others' },
  { slug: 'playing-guitar', name: 'playing guitar' },
  { slug: 'skateboarding', name: 'skateboarding' },
  { slug: 'programming', name: 'programming' },
  { slug: 'raising-chickens', name: 'raising chickens' },
  { slug: 'drinking', name: 'drinking' },
  { slug: 'gardening', name: 'gardening' },
  { slug: 'blacksmithing', name: 'blacksmithing' },
  { slug: 'science', name: 'science' },
  { slug: 'gemology', name: 'gemology' },
  { slug: 'knitting', name: 'knitting' },
  { slug: 'watching-tv', name: 'watching TV' },
  { slug: 'complaining', name: 'complaining' },
  { slug: 'playing-darts', name: 'playing darts' },
  { slug: 'playing-with-animals', name: 'playing with animals' },
  { slug: 'drawing', name: 'drawing' },
  { slug: 'exercising', name: 'exercising' },
  { slug: 'hunting', name: 'hunting' },
  { slug: 'collecting-artifacts', name: 'collecting artifacts' },
  { slug: 'playing-chess', name: 'playing chess' },
  { slug: 'stargazing', name: 'stargazing' },
  { slug: 'camping', name: 'camping' },
  { slug: 'governing', name: 'governing' },
  { slug: 'history', name: 'history' },
  { slug: 'geography', name: 'geography' },
  { slug: 'taking-care-of-animals', name: 'taking care of animals' },
  { slug: 'business', name: 'business' },
  { slug: 'carpentry', name: 'carpentry' },
  { slug: 'exploring', name: 'exploring' },
  { slug: 'collecting-rare-items', name: 'collecting rare items' },
  { slug: 'playing-with-friends', name: 'playing with friends' },
  { slug: 'alchemy', name: 'alchemy' },
  { slug: 'potion-brewing', name: 'potion brewing' },
  { slug: 'divination', name: 'divination' }
]

hobbies.each do |hobby|
    Hobby.find_or_create_by(hobby)
end

gifts = [
  { slug: 'amethyst', name: 'Amethyst' },
  { slug: 'banana-pudding', name: 'Banana Pudding' },
  { slug: 'blackberry-cobbler', name: 'Blackberry Cobbler' },
  { slug: 'chocolate-cake', name: 'Chocolate Cake' },
  { slug: 'monster-compendium', name: 'Monster Compendium' },
  { slug: 'pufferfish', name: 'Pufferfish' },
  { slug: 'pumpkin', name: 'Pumpkin' },
  { slug: 'spicy-eel', name: 'Spicy Eel' },
  { slug: 'complete-breakfast', name: 'Complete Breakfast' },
  { slug: 'jack-be-nimble-jack-be-thick', name: 'Jack Be Nimble, Jack Be Thick' },
  { slug: 'salmon-dinner', name: 'Salmon Dinner' },
  { slug: 'crab-cakes', name: 'Crab Cakes' },
  { slug: 'duck-feather', name: 'Duck Feather' },
  { slug: 'lobster', name: 'Lobster' },
  { slug: 'pomegranate', name: 'Pomegranate' },
  { slug: 'squid-ink', name: 'Squid Ink' },
  { slug: 'tom-kha-soup', name: 'Tom Kha Soup' },
  { slug: 'aquamarine', name: 'Aquamarine' },
  { slug: 'cloth', name: 'Cloth' },
  { slug: 'emerald', name: 'Emerald' },
  { slug: 'jade', name: 'Jade' },
  { slug: 'ruby', name: 'Ruby' },
  { slug: 'survival-burger', name: 'Survival Burger' },
  { slug: 'topaz', name: 'Topaz' },
  { slug: 'wool', name: 'Wool' },
  { slug: 'coconut', name: 'Coconut' },
  { slug: 'fruit-salad', name: 'Fruit Salad' },
  { slug: 'pink-cake', name: 'Pink Cake' },
  { slug: 'sunflower', name: 'Sunflower' },
  { slug: 'coffee', name: 'Coffee' },
  { slug: 'pickles', name: 'Pickles' },
  { slug: 'super-meal', name: 'Super Meal' },
  { slug: 'truffle-oil', name: 'Truffle Oil' },
  { slug: 'wine', name: 'Wine' },
  { slug: 'goat-cheese', name: 'Goat Cheese' },
  { slug: 'poppyseed-muffin', name: 'Poppyseed Muffin' },
  { slug: 'salad', name: 'Salad' },
  { slug: 'stir-fry', name: 'Stir Fry' },
  { slug: 'truffle', name: 'Truffle' },
  { slug: 'vegetable-medley', name: 'Vegetable Medley' },
  { slug: 'battery-pack', name: 'Battery Pack' },
  { slug: 'cauliflower', name: 'Cauliflower' },
  { slug: 'cheese-cauliflower', name: 'Cheese Cauliflower' },
  { slug: 'diamond', name: 'Diamond' },
  { slug: 'gold-bar', name: 'Gold Bar' },
  { slug: 'iridium-bar', name: 'Iridium Bar' },
  { slug: 'miner\'s-treat', name: 'Miner\'s treat' },
  { slug: 'pepper-poppers', name: 'Pepper Poppers' },
  { slug: 'radioactive-bar', name: 'Radioactive Bar' },
  { slug: 'rhubarb-pie', name: 'Rhubarb Pie' },
  { slug: 'strawberry', name: 'Strawberry' },
  { slug: 'emerald', name: 'Emerald' },
  { slug: 'melon', name: 'Melon' },
  { slug: 'poppy', name: 'Poppy' },
  { slug: 'red-plate', name: 'Red Plate' },
  { slug: 'roots-platter', name: 'Roots Platter' },
  { slug: 'sandfish', name: 'Sandfish' },
  { slug: 'cactus-fruit', name: 'Cactus Fruit' },
  { slug: 'maple-bar', name: 'Maple Bar' },
  { slug: 'pizza', name: 'Pizza' },
  { slug: 'tigerseye', name: 'Tigerseye' },
  { slug: 'frozen-tear', name: 'Frozen Tear' },
  { slug: 'obsidian', name: 'Obsidian' },
  { slug: 'pumpkin-soup', name: 'Pumpkin Soup' },
  { slug: 'sashimi', name: 'Sashimi' },
  { slug: 'void-egg', name: 'Void Egg' },
  { slug: 'beer', name: 'Beer' },
  { slug: 'hot-pepper', name: 'Hot Pepper' },
  { slug: 'fish-taco', name: 'Fish Taco' },
  { slug: 'green-tea', name: 'Green Tea' },
  { slug: 'summer-spangle', name: 'Summer Spangle' },
  { slug: 'tropical-curry', name: 'Tropical Curry' },
  { slug: 'artichoke-dip', name: 'Artichoke Dip' },
  { slug: 'fiddlehead-risotto', name: 'Fiddlehead Risotto' },
  { slug: 'omni-geode', name: 'Omni Geode' },
  { slug: 'bean-hotpot', name: 'Bean Hotpot' },
  { slug: 'ice-cream', name: 'Ice Cream' },
  { slug: 'rice-pudding', name: 'Rice Pudding' },
  { slug: 'lemon-stone', name: 'Lemon Stone' },
  { slug: 'fairy-rose', name: 'Fairy Rose' },
  { slug: 'stuffing', name: 'Stuffing' },
  { slug: 'tulip', name: 'Tulip' },
  { slug: 'raisins', name: 'Raisins' },
  { slug: 'fried-mushroom', name: 'Fried Mushroom' },
  { slug: 'leek', name: 'Leek' },
  { slug: 'escargot', name: 'Escargot' },
  { slug: 'orange', name: 'Orange' },
  { slug: 'pink-cake', name: 'Pink Cake' },
  { slug: 'plum-pudding', name: 'Plum Pudding' },
  { slug: 'crispy-bass', name: 'Crispy Bass' },
  { slug: 'eggplant-parmesan', name: 'Eggplant Parmesan' },
  { slug: 'fried-eel', name: 'Fried Eel' },
  { slug: 'pancakes', name: 'Pancakes' },
  { slug: 'roasted-hazelnuts', name: 'Roasted Hazelnuts' },
  { slug: 'monster-compendium', name: 'Monster Compendium' },
  { slug: 'void-mayonnaise', name: 'Void Mayonnaise' },
  { slug: 'wild-horseradish', name: 'Wild Horseradish' },
  { slug: 'mango', name: 'Mango' },
  { slug: 'ostrich-egg', name: 'Ostrich Egg' },
  { slug: 'poi', name: 'Poi' },
  { slug: 'autumn\'s-bounty', name: 'Autumn\'s Bounty' },
  { slug: 'glazed-yams', name: 'Glazed Yams' },
  { slug: 'hot-pepper', name: 'Hot Pepper' },
  { slug: 'blueberry-tart', name: 'Blueberry Tart' },
  { slug: 'dish-o\'-the-sea', name: 'Dish O\' The Sea' },
  { slug: 'yam', name: 'Yam' },
  { slug: 'farmer\'s-lunch', name: 'Farmer\'s Lunch' },
  { slug: 'pumpkin-pie', name: 'Pumpkin Pie' },
  { slug: 'mead', name: 'Mead' },
  { slug: 'pale-ale', name: 'Pale Ale' },
  { slug: 'parsnip', name: 'Parsnip' },
  { slug: 'parsnip-soup', name: 'Parsnip Soup' },
  { slug: 'piña-colada', name: 'Piña Colada' },
  { slug: 'fried-calamari', name: 'Fried Calamari' },
  { slug: 'price-catalogue', name: 'Price Catalogue' },
  { slug: 'spaghetti', name: 'Spaghetti' },
  { slug: 'woody\'s-secret', name: 'Woody\'s Secret' },
  { slug: 'crocus', name: 'Crocus' },
  { slug: 'goat-cheese', name: 'Goat Cheese' },
  { slug: 'pizza', name: 'Pizza' },
  { slug: 'salad', name: 'Salad' },
  { slug: 'stir-fry', name: 'Stir Fry' },
  { slug: 'truffle', name: 'Truffle' },
  { slug: 'vegetable-medley', name: 'Vegetable Medley' },
  { slug: 'blueberry', name: 'Blueberry' },
  { slug: 'chocolate-cake', name: 'Chocolate Cake' },
  { slug: 'corn', name: 'Corn' },
  { slug: 'diamond', name: 'Diamond' },
  { slug: 'prismatic-shard', name: 'Prismatic Shard' },
  { slug: 'spaghetti', name: 'Spaghetti' },
  { slug: 'strawberry', name: 'Strawberry' },
  { slug: 'rabbit\'s-foot', name: 'Rabbit\'s Foot' },
  { slug: 'cactus-fruit', name: 'Cactus Fruit' },
  { slug: 'maple-bar', name: 'Maple Bar' },
  { slug: 'pizza', name: 'Pizza' },
  { slug: 'tigerseye', name: 'Tigerseye' },
  { slug: 'pina-colada', name: 'Piña Colada' },
  { slug: 'cheese', name: 'Cheese' },
  { slug: 'eggplant-parmesan', name: 'Eggplant Parmesan' },
  { slug: 'fried-eel', name: 'Fried Eel' },
  { slug: 'pancakes', name: 'Pancakes' },
  { slug: 'roasted-hazelnuts', name: 'Roasted Hazelnuts' },
  { slug: 'fried-calamari', name: 'Fried Calamari' },
  { slug: 'spaghetti', name: 'Spaghetti' },
  { slug: 'rhubarb-pie', name: 'Rhubarb Pie' },
  { slug: 'strawberry', name: 'Strawberry' },
  { slug: 'emerald', name: 'Emerald' },
  { slug: 'melon', name: 'Melon' },
  { slug: 'poppy', name: 'Poppy' },
  { slug: 'red-plate', name: 'Red Plate' },
  { slug: 'roots-platter', name: 'Roots Platter' },
  { slug: 'sandfish', name: 'Sandfish' },
  { slug: 'sunfish', name: 'Sunfish' },
  { slug: 'cactus-fruit', name: 'Cactus Fruit' },
  { slug: 'maple-bar', name: 'Maple Bar' },
  { slug: 'pizza', name: 'Pizza' },
  { slug: 'tigerseye', name: 'Tigerseye' },
  { slug: 'pumpkin-soup', name: 'Pumpkin Soup' },
  { slug: 'sashimi', name: 'Sashimi' },
  { slug: 'void-egg', name: 'Void Egg' },
  { slug: 'beer', name: 'Beer' },
  { slug: 'hot-pepper', name: 'Hot Pepper' },
  { slug: 'fish-taco', name: 'Fish Taco' },
  { slug: 'green-tea', name: 'Green Tea' },
  { slug: 'summer-spangle', name: 'Summer Spangle' },
  { slug: 'tropical-curry', name: 'Tropical Curry' },
  { slug: 'void-mayonnaise', name: 'Void Mayonnaise' },
  { slug: 'wild-horseradish', name: 'Wild Horseradish' },
  { slug: 'fruit-salad', name: 'Fruit Salad' },
  { slug: 'pink-cake', name: 'Pink Cake' },
  { slug: 'sunflower', name: 'Sunflower' },
  { slug: 'coffee', name: 'Coffee' },
  { slug: 'pickles', name: 'Pickles' },
  { slug: 'super-meal', name: 'Super Meal' },
  { slug: 'truffle-oil', name: 'Truffle Oil' },
  { slug: 'wine', name: 'Wine' },
  { slug: 'golden-pumpkin', name: 'Golden Pumpkin' },
  { slug: 'iridium-bar', name: 'Iridium Bar' },
  { slug: 'magic-rock-candy', name: 'Magic Rock Candy' },
  { slug: 'pearl', name: 'Pearl' },
  { slug: 'prismatic-shard', name: 'Prismatic Shard' },
  { slug: 'rabbit\'s-foot', name: 'Rabbit\'s Foot' },
  { slug: 'void-salmon', name: 'Void Salmon' },
  { slug: 'amethyst', name: 'Amethyst' },
  { slug: 'apple', name: 'Apple' },
  { slug: 'apricot', name: 'Apricot' },
  { slug: 'beer', name: 'Beer' },
  { slug: 'cherry', name: 'Cherry' },
  { slug: 'chocolate-cake', name: 'Chocolate Cake' },
  { slug: 'coconut', name: 'Coconut' },
  { slug: 'diamond', name: 'Diamond' },
  { slug: 'duck-feather', name: 'Duck Feather' },
  { slug: 'fried-mushroom', name: 'Fried Mushroom' },
  { slug: 'goat-cheese', name: 'Goat Cheese' },
  { slug: 'honey', name: 'Honey' },
  { slug: 'ice-cream', name: 'Ice Cream' },
  { slug: 'melon', name: 'Melon' },
  { slug: 'orange', name: 'Orange' },
  { slug: 'pale-ale', name: 'Pale Ale' },
  { slug: 'pina-colada', name: 'Pina Colada' },
  { slug: 'pink-cake', name: 'Pink Cake' },
  { slug: 'pomegranate', name: 'Pomegranate' },
  { slug: 'purple-mushroom', name: 'Purple Mushroom' },
  { slug: 'rainbow-shell', name: 'Rainbow Shell' },
  { slug: 'salmon-dinner', name: 'Salmon Dinner' },
  { slug: 'strawberry', name: 'Strawberry' },
  { slug: 'sweet-pea', name: 'Sweet Pea' },
  { slug: 'truffle', name: 'Truffle' },
  { slug: 'truffle-oil', name: 'Truffle Oil' },
  { slug: 'wine', name: 'Wine' }
]

gifts.each do |gift|
    Gift.find_or_create_by(gift)
end



